### ISSUE TITLE
compile failing for me

### ISSUE THREAD

**Issue by shortthefomo** [XRPLF/XRPL-Technical-Explorer#5]
```
Building for production...Error: error:0308010C:digital envelope routines::unsupported
```

<img width="1105" alt="Screen Shot 2022-12-07 at 00 37 17" src="https://user-images.githubusercontent.com/508629/206082179-60423695-02dd-4a2b-b428-6e2e88c6aa1b.png">

**Comment by WietseWind** [comment]
@lathanbritz Which node version are you running? It seems to be a problem with most recent node versions + older WebPack versions.

If you run with node16: no trouble. If you run on newer node, you can export an env var to use legacy OpenSSL with node:
```
export NODE_OPTIONS=--openssl-legacy-provider
```

... And then run `npm run serve` or `npm run build`
